### ISSUE TITLE
DatagroupsController# (NoMethodError) "undefined method `upcase!' for nil:NilClass"

### ISSUE THREAD

**Issue by befdata** [befdata/befdata#396]
<table><tr><th>Exception</th><td>undefined method `upcase!' for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>April 01, 2015 09:57:53 +0200</td></tr><tr><th>Count</th><td>13</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/befdata/befdata/blob/7aecd6065cf220fc68c9471179d213f3892c8dcd/app/models/datagroup.rb#L48'>/var/www/production/befdata/app/models/datagroup.rb:48:in `block in update_and_merge_categories_with_csv'</a>
<a href='https://github.com/befdata/befdata/blob/7aecd6065cf220fc68c9471179d213f3892c8dcd/app/models/datagroup.rb#L48'>/var/www/production/befdata/app/models/datagroup.rb:48:in `map'</a>
<a href='https://github.com/befdata/befdata/blob/7aecd6065cf220fc68c9471179d213f3892c8dcd/app/models/datagroup.rb#L48'>/var/www/production/befdata/app/models/datagroup.rb:48:in `update_and_merge_categories_with_csv'</a>
<a href='https://github.com/befdata/befdata/blob/7aecd6065cf220fc68c9471179d213f3892c8dcd/app/controllers/datagroups_controller.rb#L78'>/var/www/production/befdata/app/controllers/datagroups_controller.rb:78:in `update_categories'</a>
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:447:in `_run__445516837__process_action__636473074__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `block in action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call'
/var/lib/gems/1.9.1/gems/party_foul-1.2.2/lib/party_foul/middleware.rb:8:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__997178836__call__605004260__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/tagged_logging.rb:22:in `tagged'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/utils.rb:470:in `safe_fork'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:180:in `start'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in `synchronize'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/helper-scripts/passenger-spawn-server:99:in `<main>'</pre>

Fingerprint: `4de9eb50a423ec002ff3374acf9d4c231f62cb16`

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 13:55:57 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 13:56:07 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 13:56:34 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 13:58:31 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 14:00:41 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 14:00:54 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 25, 2015 14:06:17 +0100</td></tr><tr><th>URL</th><td>[POST] /datagroups/600/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>600</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>1b54c6eff65b293c35cc825a8b4c723b</td></tr><tr><th>_csrf_token</th><td>Md71/wTlxCj67EGy4IixVcT5uX39DduiAvax5yPaDsI=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>March 31, 2015 16:38:03 +0200</td></tr><tr><th>URL</th><td>[POST] /datagroups/1/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>1</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>292ca79a0cd22431ab09b73fb4468fa9</td></tr><tr><th>_csrf_token</th><td>Azz7PAB2Ooy7+HqHJ3/9Q72ILGe630kwfe80xOx2WGw=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>March 31, 2015 16:38:28 +0200</td></tr><tr><th>URL</th><td>[POST] /datagroups/1/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>1</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>292ca79a0cd22431ab09b73fb4468fa9</td></tr><tr><th>_csrf_token</th><td>Azz7PAB2Ooy7+HqHJ3/9Q72ILGe630kwfe80xOx2WGw=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>March 31, 2015 16:39:21 +0200</td></tr><tr><th>URL</th><td>[POST] /datagroups/1/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>1</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>292ca79a0cd22431ab09b73fb4468fa9</td></tr><tr><th>_csrf_token</th><td>Azz7PAB2Ooy7+HqHJ3/9Q72ILGe630kwfe80xOx2WGw=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>April 01, 2015 09:57:53 +0200</td></tr><tr><th>URL</th><td>[POST] /datagroups/1/update_categories</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>update_categories</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>1</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>2468f229ed5bf19c0b0eea73dab3310e</td></tr><tr><th>_csrf_token</th><td>p1jS+36uubjpPY+UQjmf63o24O76qzFNUtgj0lUcuqE=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
