### ISSUE TITLE
DatagroupsController# (SignalException) "SIGTERM"

### ISSUE THREAD

**Issue by befdata** [befdata/befdata#405]
<table><tr><th>Exception</th><td>SIGTERM</td></tr><tr><th>Last Occurrence</th><td>February 24, 2015 14:16:34 +0100</td></tr><tr><th>Count</th><td>2</td></tr></table>

## Stack Trace

<pre>/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/column.rb:175:in `value_to_integer'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/read.rb:72:in `__temp__'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/base.rb:597:in `=='
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:467:in `delete'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:467:in `block in remove_records'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:467:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:467:in `remove_records'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:459:in `block in delete_or_destroy'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:149:in `block in transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:148:in `transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:459:in `delete_or_destroy'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:231:in `delete'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:157:in `delete_all'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/collection_proxy.rb:46:in `delete_all'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/builder/has_many.rb:42:in `block in define_destroy_dependency_method'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:407:in `_run__851796305__destroy__1047584038__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/callbacks.rb:254:in `destroy'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:254:in `block in destroy'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:254:in `destroy'
<a href='https://github.com/befdata/befdata/blob/0c388e9e9ced3a1859bf878607b1c2b1b205dc79/app/controllers/datagroups_controller.rb#L58'>/var/www/production/befdata/app/controllers/datagroups_controller.rb:58:in `destroy'</a>
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:447:in `_run__235537068__process_action__398088773__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `block in action'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/var/lib/gems/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call'
/var/lib/gems/1.9.1/gems/party_foul-1.2.2/lib/party_foul/middleware.rb:8:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__294309659__call__1047584038__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/tagged_logging.rb:22:in `tagged'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call'
/var/lib/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/var/lib/gems/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
/var/lib/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/utils.rb:470:in `safe_fork'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:180:in `start'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in `synchronize'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/var/lib/gems/1.9.1/gems/passenger-3.0.18/helper-scripts/passenger-spawn-server:99:in `<main>'</pre>

Fingerprint: `7e9d6bc0862311958f62024bcf04aa4db747648e`

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 24, 2015 10:09:18 +0100</td></tr><tr><th>URL</th><td>[DELETE] /datagroups/224</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>destroy</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>224</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>ca3282afbb4ae6f546ec3c6ced472563</td></tr><tr><th>_csrf_token</th><td>PRWa9uYDaOBRjV3ArGCsLcd2PjT6GH7AMef5YkHFjIo=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by befdata** [comment]
<table><tr><th>Occurred At</th><td>February 24, 2015 14:16:34 +0100</td></tr><tr><th>URL</th><td>[DELETE] /datagroups/224</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>destroy</td></tr><tr><th>controller</th><td>datagroups</td></tr><tr><th>id</th><td>224</td></tr></table></td></tr><tr><th>Session</th><td><table><tr><th>session_id</th><td>ca3282afbb4ae6f546ec3c6ced472563</td></tr><tr><th>_csrf_token</th><td>PRWa9uYDaOBRjV3ArGCsLcd2PjT6GH7AMef5YkHFjIo=</td></tr><tr><th>user_credentials</th><td>[FILTERED]</td></tr><tr><th>user_credentials_id</th><td>[FILTERED]</td></tr></table></td></tr><tr><th>IP Address</th><td>139.18.89.75</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
